### ISSUE TITLE
ABOUT 3DHP

### ISSUE THREAD

**Issue by Aerikervalid** [bruceyo/GLA-GCN#2]
![image](https://github.com/bruceyo/GLA-GCN/assets/138544094/8d1e5136-3694-4948-b02b-b6a734320c5b)
Hi, Great Job.  I want to ask why my 3DHP dataset doesn't have a valid_frame metric. Is it because I didn't process the dataset, or because my downloaded dataset has an error. Looking forward to your reply, thank you very much!

**Comment by bruceyo** [comment]
Hi @Aerikervalid, thank you for your interest. To calculate the AUC and PCK, you should download data of all subjects (i.e., 1-6). I use the pre-proceed data and the mpii_test_predictions_py.m (which is a little different from the original one) provided by [p-stmo](https://github.com/patrick-swk/p-stmo). You also need to change the path of corresponding data to correctly run the code.

**Comment by Aerikervalid** [comment]
@bruceyo Yes, I have referred to the p-stmo steps in detail. But my downloaded 3 DHP dataset seems to be problematic. When I import the annot.m for each subject, the program tells me that the valid_frame metric is missing. Whether you can give a download link to the file (the 6 annot.m files or 3DHP dataset) you use (Google disk or Baidu disk), thank you very much!!!

**Comment by bruceyo** [comment]
@Aerikervalid sure no problem, please refer to the Google file: [mpi_inf_3dhp_test_dataset_download_code.zip](https://drive.google.com/drive/folders/1RFkIpRNR-78hu3lXF_yTxoiM6GVO0Jx9?usp=sharing).

**Comment by Aerikervalid** [comment]
@bruceyo   thanks！ The problem has been solved. You are the most handsome man in the world ！😄
