### ISSUE TITLE
Can I know to change T value to 81?

### ISSUE THREAD

**Issue by sung-sidewalk** [bruceyo/GLA-GCN#3]
Great Work! Thank you for sharing for such a great project!

I have a question though..

Is it possible to change T (frames) value into 81 or lower instead of 243 to test in low frame rate?

Thank you very much!

**Comment by bruceyo** [comment]
Hi @sung-sidewalk thank you for your interest. I have not yet tested in such as way, i.e., training with 243 frames and testing with 81 frames. Some video-based recognition models have such practice programmed, but this model might need further modification to fulfill your question.

**Comment by sung-sidewalk** [comment]
> 

Thank you very much!
I will search other models as well!!
